# Use root/example as user/password credentials
services:
  mongo:
    container_name: ${DB_CONTAINER_NAME} #this is custom field added by me
    image: mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_DATABASENAME: $(DB_NAME)
      MONGO_INITDB_ROOT_USERNAME: $(DB_USERNAME)
      MONGO_INITDB_ROOT_PASSWORD: $(DB_PASSWORD)

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
